[GLOBAL]
pants_version = "2.23.0.dev6"

build_patterns = ["BUILD.pants", "BUILD"]
pantsd = true

backend_packages = [
    "pants.backend.experimental.cc",
    "pants.backend.experimental.cc.lint.clangformat",
    "pants.backend.experimental.cue",
    "pants.backend.experimental.debian",
    "pants.backend.experimental.java",
    "pants.backend.experimental.java.lint.google_java_format",
    "pants.backend.experimental.java.debug_goals",
    "pants.backend.experimental.javascript",
    "pants.backend.experimental.javascript.lint.prettier",
    "pants.backend.experimental.kotlin",
    "pants.backend.experimental.kotlin.lint.ktlint",
    "pants.backend.experimental.makeself",
    "pants.backend.experimental.python.lint.add_trailing_comma",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
    "pants.backend.experimental.python.typecheck.pyright",
    "pants.backend.experimental.scala",
    "pants.backend.experimental.scala.lint.scalafmt",
    "pants.backend.experimental.scala.lint.scalafix",
    "pants.backend.experimental.scala.debug_goals",
    "pants.backend.experimental.tools.semgrep",
    "pants.backend.experimental.tools.trufflehog",
    "pants.backend.experimental.tools.workunit_logger",
    "pants.backend.experimental.tools.yamllint",
#    "pants.backend.experimental.python.typecheck.pytype",
    "pants.backend.experimental.sql",
    "pants.backend.experimental.sql.lint.sqlfluff",
    "pants.backend.experimental.typescript",
    "pants.backend.python",
    "pants.backend.python.lint.autoflake",
    "pants.backend.python.lint.bandit",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.pydocstyle",
    "pants.backend.python.lint.pylint",
    "pants.backend.python.lint.pyupgrade",
    "pants.backend.python.lint.yapf",
#    "pants.backend.python.typecheck.mypy",
    "pants.backend.shell",
    "pants.backend.shell.lint.shellcheck",
    "pants.backend.shell.lint.shfmt",
]

[cli.alias]
# Missing publish, repl, run for python
sanity = "update-build-files fix fmt lint check test package"

[source]
marker_filenames = ["BUILD.pants"]

[python]
interpreter_constraints = ["==3.11.*"]

[bandit]
# Skipping assertion warnings - because this is an example project
args = ["--skip B101"]

[pydocstyle]
# Ignore module and package docs
args = ["--match=`!*_test.py`", "--ignore=D100,D104"]

[pylint]
args = ["--ignore=greeter_test.py"]

[pyright]
version = "pyright@1.1.360"

[workunit-logger]
enabled = true